services:
  - type: web
    name: srf-backend
    env: node
    buildCommand: npm install && npm run build --workspace=srf-backend
    startCommand: npm run start:prod --workspace=srf-backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: PORT
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: EMAIL_HOST
        sync: false
      - key: EMAIL_PORT
        sync: false
      - key: SENDER_NAME
        sync: false
      - key: SENDER_EMAIL
        sync: false
      - key: SENDER_PASSWORD
        sync: false